### ISSUE TITLE
ModelMetadataInfo enforces subgraphs to exist

### ISSUE THREAD

**Issue by hohteri** [tensorflow/tflite-support#187]
I'm using model metadata to store model version number and to read it back but there is an assert that gets triggered. I don't want to use the subgraph metadata at all:

https://github.com/tensorflow/tflite-support/blob/db5e8cc6f0b89cba001385c0dbf7bf0cbf4d2224/tensorflow_lite_support/metadata/java/src/java/org/tensorflow/lite/support/metadata/ModelMetadataInfo.java#L56

Is this check intentional or a mistake?

**Comment by hohteri** [comment]
Interestingly on Linux it does enforce it when creating metadata:

`line 28, in <module>
    populator.load_metadata_buffer(metadata_buf)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_lite_support/metadata/metadata.py", line 269, in load_metadata_buffer
    self._validate_metadata(metadata_buf)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_lite_support/metadata/metadata.py", line 521, in _validate_metadata
    model_meta.SubgraphMetadataLength()))
ValueError: The number of SubgraphMetadata should be exactly one, but got 0.`

But on macOS not.

**Comment by lu-wang-g** [comment]
Yes. The subgraph and tensor check has not been implemented in the C++ metadata extractor lib yet, but the Java lib. 

The check is mainly to enforce that the metadata info is valid so that the [AS model binding [feature]](https://www.tensorflow.org/lite/inference_with_metadata/codegen#generate_code_with_android_studio_ml_model_binding) and [Task library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview) can work properly. But I think allowing zero in this case should be fine. 

At the mean time, to unblock your work, please try creating an empty subgraph object to your metadata. Thanks!

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen it if you have other questions.
