### ISSUE TITLE
Tflite Quant inference is slower than TFlite float32 on Intel CPU

### ISSUE THREAD

**Issue by shivSD** [tensorflow/tflite-support#214]
I have converted a network into TFlite using DEFAULT optimization (Float32) setting and its inference speed is around 25 fps. Same network when i converted into TFlite INT8 Quantized and its inference speed is around 2 fps on INTEL 8-Core Intel Core i9 2.3 GHz. Is this expected on CPU?  Please can somebody explain what causes the slowness of INT8 inference.

**Comment by multiverse-tf** [comment]
Sorry for the late response.

Such performance behavior you described isn't surprising (:-)) because those quant kernels haven't been optimized as much as those corresponding float kernels on Intel CPUs (i.e. x86_64).  But if you try it out on mobile phones, you will find that quant inference generally outperforms their float counterpart.

We have been aware of such performance discrepancy, and we have been working on to optimize these quant kernels on x86_64 platforms. I think more recent TFLite builds (say, the tflite nightly) should start to deliver better performance on x86_64 for quant models. @talumbau will be able to shed more light on this.

**Comment by ben-xD** [comment]
Thanks for the details @multiverse-tf, I would appreciate more info on this too, if @talumbau could give it a go? 🥇 

x86 is falling behind

**Comment by talumbau** [comment]
Hi, thanks for opening the issue. This Github project is about the TF Lite Support library, rather than a place for "support" for TF Lite. In order to proceed here, can you please open a new issue for "Performance" here:

https://github.com/tensorflow/tensorflow/issues/new/choose

and then fill in the template with the relevant details and assign to me? Cheers!
