### ISSUE TITLE
tflite model giving extremely FPS

### ISSUE THREAD

**Issue by AryanSethi** [tensorflow/tflite-support#448]
I'm trying to run [this](https://tfhub.dev/intel/lite-model/midas/v2_1_small/1/lite/1) tflite model and it's taking about 0.5 seconds for prediction on each frame. While on android and iOS phones, it gives over 20 FPS.

Refer to [my issue](https://github.com/intel-isl/MiDaS/issues/97) for more details

**Comment by lu-wang-g** [comment]
By "0.5 seconds", do you mean to run it on desktop? If so, it is expected, because TFLite is not specifically optimized for desktop. You can try running tflite with [xnnpack](https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html) (soon, xnnpack will become default), or using the [Coral EdgeTpu delegate](https://coral.ai/docs/edgetpu/tflite-cpp/#set-up-the-tf-lite-interpreter-with-libedgetpu).

**Comment by AryanSethi** [comment]
@lu-wang-g
Yes, I was running the script on my desktop and as I could see, it wasn't even using my GPU.
So will running it on any edge device solve the problem?

**Comment by lu-wang-g** [comment]
I don't think tflite is supported on desktop GPU. Running on Coral edgetpu will give you 20x ~ 60x speed up.
