### ISSUE TITLE
tflite quantized model producing different results on CPU / NNAPI+NPU

### ISSUE THREAD

**Issue by FSet89** [tensorflow/tflite-support#543]
I have a quantized tflite model that is deployed on a system equipped with a NPU and NNAPI. I noticed that the same module produces different outputs when the inference is performed on a CPU instead of NPU+NNAPI. Sometimes the differences are very high. What is the reason for this?

**Comment by wangtz** [comment]
Hi There,

Thanks for reporting the issue. Task library calls TFLite underneath for the invocation on CPU v.s. NNAPI. 

If the CPU results are correct (the same as TF in training), then it might be an issue with NNAPI or vendor (NPU chip vendor) implementation.

If the CPU results are incorrect, it might be an issue with TFLite implementation.

In either cases, please raise the issue in https://github.com/tensorflow/tensorflow so that the TFLite team can have a look :-) Please attach the model, input data, expected output and actual output data, together with some specs on the actual devices that you're using.

Thanks,
Tiezhen

**Comment by lu-wang-g** [comment]
@FSet89 can you please also provide the code snippet of how your inference is done? I guess the Support Library is used, right? As Tiezhen said, it will be great if you know which inference is correct, CPU or NNAPI.

**Comment by xunkai55** [comment]
Also discovered CPU / GPU difference in https://github.com/tensorflow/tflite-support/issues/534#issuecomment-862342445.
