### ISSUE TITLE
ModuleNotFoundError: No module named 'tflite_support.task'

### ISSUE THREAD

**Issue by bbartling** [tensorflow/tflite-support#899]
Hi,

I have a rasp pi B+ running Buster image Python 3.7.3:
```
>>> print(tflite_support.__version__)
0.1.0a1
>>> import tflite_support.task
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tflite_support.task'
>>> 
```

Hoping to try out some computer vision code:
```
from tflite_support.task import core
from tflite_support.task import processor
from tflite_support.task import vision
```

Would there be any work arounds or fixes to try? Also NOT using Coral Edge TPU

**Comment by lu-wang-g** [comment]
tflite_support 0.1.0 does not have the `task` module. You need a version of 0.4 and above. Check out the latest version here: https://pypi.org/project/tflite-support/.

Double check if any of the [prebuilt binaries](https://pypi.org/project/tflite-support/0.4.3/#files) fits your specific system and setup. Since you installed version 0.1.0, mostly likely none of those fit, so it ended up building a very old version of tflite_support on your machine (unlike the later versions, v0.1.0 builds the wheels on your machine, and then installs). Alternatively, you can build your own wheels. See the instruction here: https://github.com/tensorflow/tflite-support/issues/755#issuecomment-1060998000

**Comment by bbartling** [comment]
Thank you....
