### ISSUE TITLE
TensorFlowLiteTaskVision linking error for arm64

### ISSUE THREAD

**Issue by yoching** [tensorflow/tflite-support#908]
Hello.
I tried to use `TensorFlowLiteTaskVision` for an iOS app and installed it with CocoaPods, however, the build fails when I build for simulators. It builds when I target physical devices. I'm using M1 MacBookAir.

This is the error and the screenshot.
```
In /Users/yoshikuni/2022/12SwiftCharts/experiments/TensorFlowDependencyExperiment/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision(TFLImageClassifier.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/yoshikuni/2022/12SwiftCharts/experiments/TensorFlowDependencyExperiment/Pods/TensorFlowLiteTaskVision/Frameworks/TensorFlowLiteTaskVision.framework/TensorFlowLiteTaskVision' for architecture arm64
```

<img width="1196" alt="Screenshot 2022-12-30 at 16 09 47" src="https://user-images.githubusercontent.com/3376690/210084937-7d4fbeeb-57c6-4525-b965-989441e9736e.png">

Do you know how to solve this problem?

Thank you in advance!

**Comment by yoching** [comment]
This is my Podfile.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TensorFlowDependencyExperiment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TensorFlowDependencyExperiment
  pod 'TensorFlowLiteTaskVision'

  target 'TensorFlowDependencyExperimentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TensorFlowDependencyExperimentUITests' do
    # Pods for testing
  end

end
```

**Comment by pankazS1ngh** [comment]
Enable Rosetta for Xcode.
For Xcode 14.3.1:Go to  Xcode top menu 
Product->Destination->Destination Architecture->Show Both.
Now select the simulator with the suffix (Rosetta). like iPhone 14 (Rosetta)

**Comment by lu-wang-g** [comment]
Thanks @pankazS1ngh for helping out!

Closing this issue for now as it goes stale. Feel free to reopen.

**Comment by marcosliberal** [comment]
Hi,

The issue seems to be similar to [this one](https://github.com/tensorflow/tensorflow/issues/47400) on TensorFlow Lite, that was already solved.

Using a Rosetta simulator like @pankazS1ngh suggested is a workaround for compiling and running an application on the simulator with TensorFlowLiteTaskVision, but it does not solve some annoying issues with storyboards. If you have a storyboard where you include some reusable Views on .xib files, they will not render because the storyboard relies on compiling the xibs for the arm simulator.

Would it be possible to reopen this issue and take a look at it?

Thanks!
